services:
#MariaDB Container
  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    hostname: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - ./mariadb.env
    restart: always
    networks:
      - minha_rede

#GLPI Container
  glpi:
    image: glpi/glpi:11.0.8
    container_name : glpi
    hostname: glpi
    ports:
      - "8083:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - ./data/localtime/Sao_Paulo:/etc/localtime:ro
      # - ./data/www/glpi:/var/www/html/glpi
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glpi.rule=Host(`suporte.computocell.com.br`)"
      - "traefik.http.routers.glpi.entrypoints=websecure"
      - "traefik.docker.network=minha_rede"
      - "traefik.http.routers.glpi.tls=true"
      - "traefik.http.routers.glpi.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.glpi.loadbalancer.server.port=80"
    environment:
      - TIMEZONE=AMERICA/Sao_Paulo
    restart: always
    networks:
      - minha_rede

volumes:
  mariadb_data:

networks:
  minha_rede:
    external: true