services:
# MariaDB Container
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    hostname: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${SENHA_ROOT}
      - MARIADB_DATABASE=${DATABASE_NAME}
      - MARIADB_USER=${USUARIO_GLPI}
      - MARIADB_PASSWORD=${SENHA_GLPI}
    restart: unless-stopped
    networks:
      - minha_rede

#GLPI Container
  glpi:
    image: glpi/glpi:11.0.9
    container_name : glpi
    hostname: glpi
    ports:
      - "8083:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /usr/share/zoneinfo/America/Sao_Paulo:/etc/localtime:ro
      # - ./data/www/glpi:/var/www/html/glpi
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glpi.rule=Host(`suporte.computocell.com.br`)"
      - "traefik.http.routers.glpi.entrypoints=websecure"
      - "traefik.docker.network=minha_rede"
      - "traefik.http.routers.glpi.tls=true"
      - "traefik.http.routers.glpi.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.glpi.loadbalancer.server.port=80"
    environment:
      - TIMEZONE=AMERICA/Sao_Paulo
    restart: unless-stopped
    networks:
      - minha_rede

volumes:
  postgres_data:

networks:
  minha_rede:
    external: true